import "./globals.css";
import { Inter, Signika_Negative } from "next/font/google";
import Link from "next/link";
import LoginButton from "./loginButton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutButton from "./logoutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <div>
            <Link href="/" className="logo">
              Appleforum
            </Link>
            <Link href="/list">List</Link>
          </div>
          <div>
            {session == null ? (
              <LoginButton />
            ) : (
              <>
                <div className="login-container">
                  <div>{session.user.name}님 안녕하세요!</div>
                  <LogoutButton />
                </div>
              </>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
